version: "2"
services:
  db:
    image: postgres:11.5-alpine
    container_name: "nate-mlb-db"
    ports:
      - "54320:${DATABASE_PORT}" # DATABASE_PORT on container maps to 54320 on the docker host
    volumes:
      - ./.pgdata:/var/lib/postgresql/data # save data to .pgdata
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
  web:
    build: .
    container_name: "nate-mlb-web"
    ports:
      - "8000:${PORT}" # PORT on container maps to 8000 on docker host
    environment:
      - PORT=${PORT}
      - DATABASE_URL=postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_NAME}?sslmode=disable
      - APPLICATION_NAME=nate-mlb
      # - ADMIN_PASSWORD=
      # - PLAYER_TYPES=
    depends_on:
      - db